V idia stake
ImpossibleFinance/launchpad-contracts pull request #25
Opened 2022-03-15 04:00 UTC by mkc306

2022-03-15 04:03 UTC, acceleratedmonkey commented on contracts/vIDIA.sol
> +        _mint(msg.sender,amount);
need the safeTransfer function to get the idia token

2022-03-15 04:03 UTC, acceleratedmonkey commented
please provide unit test

2022-03-15 04:08 UTC, acceleratedmonkey commented on contracts/vIDIA.sol
> +        totalStakedAmount += amount;
we still need require, check if staking enabled

2022-03-15 04:09 UTC, acceleratedmonkey requested changes
please fix all the comments

2022-03-15 13:08 UTC, acceleratedmonkey commented on contracts/vIDIA.sol
> +        stakedTokens.safeTransferFrom(_msgSender(), address(this), amount);
@impossible-pascal can u confirm is this way of safe transfer correct?

2022-03-16 02:09 UTC, impossible-pascal commented on contracts/vIDIA.sol
> +        stakedTokens.safeTransferFrom(_msgSender(), address(this), amount);
lgtm

2022-03-16 02:09 UTC, impossible-pascal commented on contracts/vIDIA.sol
> +        _mint(_msgSender(),amount);
small nit: add space after the comma

2022-03-16 02:30 UTC, impossible-pascal commented on contracts/vIDIA.sol
> +    function claimReward() public {
should merge the PR with this function uncommented. there should be errors b/c this function still thinks its n underlying tokens under a vidia contract. after correcting that, there shouldnt be any more errors

2022-03-16 02:30 UTC, impossible-pascal commented on test/test-vIDIA.ts
> +    const testAddress = '0x777788889999AaAAbBbbCcccddDdeeeEfFFfCcCc'
test address doesnt seem to have a purpose in testing, recommend switching to owner in all the vidia contract deploys

2022-03-16 02:30 UTC, impossible-pascal commented on test/test-vIDIA.ts
>      mineNext()
after changing the hardhat network settings we shouldnt need to mine blocks in testnet, can remove all instances of mineBlock() also

2022-03-16 02:30 UTC, impossible-pascal commented on test/test-vIDIA.ts
> +    await VestToken.transfer(vester.address, '1000') //times out here
for readability/cleaner code, usually we declare numbers as constants, especially if we're reusing the numbers. can try:

1. for approve, try "import { MaxUint256 } from 'ethers/constants';" and approve MaxUint256 would be better
2. can do const firstStakeAmt = 100, const secondStakeAmt = 250 and use the constants in totalStaked. then for the tests do ".to.eq(firstStakeAmt + secondStakeAmt)"

2022-03-16 02:30 UTC, impossible-pascal commented on test/test-vIDIA.ts
> +    expect(totalStakers).to.eq(2)
this is within scope of PR but a bit more complicated so we can KIV for the future.. whats the use of the totalStakers variable? this var doesnt seem to be something we need in the logic of VIDIA at all, its more of something thats extra to provide us with stats that we otherwise cant obtain that easily

currently this would track number of staking instances. personally i think it might be more useful (for front end, internal stats etc) to track unique addresses owning VIDIA instead

@acceleratedmonkey any thoughts for totalstakers?

2022-03-16 02:59 UTC, impossible-pascal commented on test/test-vIDIA.ts
> +    await VestToken.transfer(vester.address, '1000') //times out here
for #1 dont need to import, can use ethers.constants.MaxUint256 as a variable

2022-03-16 13:39 UTC, acceleratedmonkey commented on test/test-vIDIA.ts
> +    expect(totalStakers).to.eq(2)
yes the totalStakers is only for stats purposes, it's to make it easier to retreive the stats from front end,

is there any concern from your side if we keep this function?

2022-03-16 15:54 UTC, impossible-pascal approved these changes

2022-03-17 02:48 UTC, acceleratedmonkey commented on contracts/vIDIA.sol
> +        claimReward();
move this to above

2022-03-17 02:48 UTC, acceleratedmonkey commented on contracts/vIDIA.sol
> +        require(amount != 0, 'User cannot stake 0 tokens');
can remove

2022-03-17 02:48 UTC, acceleratedmonkey commented on contracts/vIDIA.sol
> +        totalStakers += 1;
lets remove for now

2022-03-17 02:53 UTC, acceleratedmonkey approved these changes

2022-03-17 02:54 UTC, merged